clone_folder: c:\gopath\src\github.com\GoogleContainerTools\skaffold
stack: go 1.10
environment:
  GOPATH: c:\gopath
build_script:
  - go build -o out/skaffold.exe cmd/skaffold/skaffold.go
test_script:
  - go test ./...
artifacts:
  - path: out/skaffold.exe
    name: skaffold