steps:

# Download the latest version of the docs-controller image
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/docs-controller:latest || exit 0
  # until https://github.com/GoogleCloudPlatform/cloud-builders/issues/253 is fixed

# Build and push latest version of the docs-controller image
- name: gcr.io/cloud-builders/docker
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/docs-controller:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/docs-controller:latest'
  - '--target'
  - 'runtime_deps'
  - 'deploy/webhook'

- name: gcr.io/$PROJECT_ID/docs-controller:latest
  env:
    - 'HUGO_ENV=production'
  args:
  - 'bash'
  - '-xc'
  - |
    deploy/docs/build.sh https://skaffold-latest.firebaseapp.com && cd docs && firebase deploy --only hosting:head --project $PROJECT_ID

images:
- 'gcr.io/$PROJECT_ID/docs-controller:latest'
