# using default substitutions, provided by Google Cloud Build
# see: https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile'
    - '.'

# Do the go build & push the results to GCS
  - name: 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    args:
    - 'make'
    - 'release-build'
    - 'RELEASE_BUCKET=$_RELEASE_BUCKET'
    - 'GCP_PROJECT=$PROJECT_ID'

# Check that skaffold is in the image
  - name: 'gcr.io/$PROJECT_ID/skaffold:edge'
    args:
    - 'skaffold'
    - 'version'

images:
- 'gcr.io/$PROJECT_ID/skaffold:edge'
- 'gcr.io/$PROJECT_ID/skaffold:$COMMIT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1200s
