# using default substitutions, provided by Google Cloud Build
# see: https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:

# Download the latest version of the builder image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/skaffold-builder:latest || exit 0
# until https://github.com/GoogleCloudPlatform/cloud-builders/issues/253 is fixed

# Rebuild the builder image if necessary
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    - '--target'
    - 'builder'
    - '.'

# Do the go build & push the results to GCS
  - name: 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    args:
    - 'make'
    - '-j'
    - 'release-build'
    - 'RELEASE_BUCKET=$_RELEASE_BUCKET'
    - 'GCP_PROJECT=$PROJECT_ID'

images:
- 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
- 'gcr.io/$PROJECT_ID/skaffold:edge'
- 'gcr.io/$PROJECT_ID/skaffold:$COMMIT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1200s
