name: Cross-Compile skaffold on MacOS

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    name: Cross-Compile skaffold on MacOS
    runs-on: macos-15-large
    strategy:
      matrix:
        platforms: [linux-amd64, darwin-amd64, windows-amd64.exe, linux-arm64, darwin-arm64]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Docker
      uses: docker/setup-docker-action@v4
      env:
        LIMA_START_ARGS: --mount-writable
    
    - name: Make and install Skaffold binary from current PR
      run: |
        make ./out/VERSION
        make ./out/skaffold-${{ matrix.platforms }}" 
